# generated by https://github.com/kylewaldner/emacs.d.git
# used for managing the emacs server client, which needs to be a different version on some systems
# also includes aliases for the emacsclient command

export EMACS_SERVER_PATH="$HOME/emacs/server_emacs/bin"


function emacsclient() {
    if [[ "$#" -lt 1 ]]; then
        $EMACS_SERVER_PATH/emacsclient -c -n -e \
                                       "(select-frame-set-input-focus (selected-frame))"
    else
        $EMACS_SERVER_PATH/emacsclient -c -n -e \
                                       "(select-frame-set-input-focus (selected-frame))" \
                                       "(find-file \"$1\")"
    fi
}

# Set emacsclient as the default editor
export EDITOR="$EMACS_SERVER_PATH/emacsclient -c"
export ALTERNATE_EDITOR="nano"

alias em="emacsclient"
