# generated by https://github.com/kylewaldner/emacs.d.git
# used for managing the emacs server client, which needs to be a different version on some systems
# also includes aliases for the emacsclient command

export EMACS_SERVER_PATH="$HOME/emacs/server_emacs/bin"

# Set emacsclient as the default editor
export EDITOR="$EMACS_SERVER_PATH/emacsclient -c"
export ALTERNATE_EDITOR="nano"

alias emacsclient="$EMACS_SERVER_PATH/emacsclient -c"
alias em="$EMACS_SERVER_PATH/emacsclient -n -c"  # emacsclient no-wait (background)
alias emm="emacsclient"
alias emt="$EMACS_SERVER_PATH/emacsclient -t"     # emacsclient in terminal
